# Generated by Django 2.2.4 on 2019-09-01 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190901_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='bcardno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_booking_card', related_query_name='main_bookings', to='main.Client'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='bempno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_booking_emp', related_query_name='main_bookings', to='main.Employee'),
        ),
    ]
